// <auto-generated />
using System;
using Gyldendal.Customer.Data.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gyldendal.Customer.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gyldendal.Customer.Data.Entities.Customer", b =>
                {
                    b.Property<int>("customerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("customerid"));

                    b.Property<int?>("customertypeid")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ssn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("customerid");

                    b.HasIndex("customertypeid");

                    b.HasIndex("ssn")
                        .IsUnique();

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Gyldendal.Customer.Data.Entities.CustomerType", b =>
                {
                    b.Property<int>("customertypeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("customertypeid"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("customertypeid");

                    b.ToTable("CustomerType");
                });

            modelBuilder.Entity("Gyldendal.Customer.Data.Entities.Customer", b =>
                {
                    b.HasOne("Gyldendal.Customer.Data.Entities.CustomerType", "customertype")
                        .WithMany("customers")
                        .HasForeignKey("customertypeid");

                    b.Navigation("customertype");
                });

            modelBuilder.Entity("Gyldendal.Customer.Data.Entities.CustomerType", b =>
                {
                    b.Navigation("customers");
                });
#pragma warning restore 612, 618
        }
    }
}
